#!/usr/bin/perl -w

# -*- cperl -*-

=head1 NAME

bcm2708_temp - Munin plugin to monitor BCM2708 CPU Temperature on a Raspberri Pi with a propertary sensor tool

=head1 APPLICABLE SYSTEMS

Any Raspberry Pi

=head1 CONFIGURATION

None needed

=head1 USAGE

Link this plugin to /etc/munin/plugins/ and restart the munin-node.

=head1 INTERPRETATION

The plugin simply shows the PU Temperature on a Raspberri Pi.

=head1 MAGIC MARKERS

  #%# family=auto
  #%# capabilities=autoconf

=head1 VERSION

  $Id$

=head1 BUGS

None known

=head1 AUTHOR

Unknown

=head1 LICENSE

/etc/munin/plugins/interrupts was used as template
GPLv2

=cut

use Munin::Plugin;
use strict;
use warnings;

my $DEBUG=1;

if (defined $ARGV[0] && $ARGV[0] eq 'autoconf') {
    if(-r '/opt/vc/bin/vcgencmd') {
	print "yes\n";
	exit(0);
    } else {
	print "no\n";
	exit(1);
    }
}

my $in;
my @cpus;
my @irqs;

if (defined $ARGV[0] && $ARGV[0] eq 'config') {
print <<EOM;
graph_title Raspberry Pi CPU temperature
graph_args --base 1000 -l 0
graph_vlabel graph_vlabel temp in °C 
graph_category sensors
graph_info This graph shows the CPU temperature in degrees Celsius of a Raspberry Pi. 
EOM
} else {
    print "cpu.value ", rand(10)+40 , "\n";
}

__END__
