#!/usr/bin/perl -w

#** @file HidTEMPer.pl
# @verbatim
#####################################################################
# This program is not guaranteed to work at all, and by using this  #
# program you release the author of any and all liability.          #
#                                                                   #
# You may use this code as long as you are in compliance with the   #
# license (see the LICENSE file) and this notice, disclaimer and    #
# comment box remain intact and unchanged.                          #
#                                                                   #
# Class:       bcmHidTEMPer                                         #
# Description: munin plugin for HidTEMPer sensor                    #
#                                                                   #
# Written by:  Imran Shamshad (sid@projekt-turm.de)                 #
##################################################################### 
# @endverbatim
#
# @copy 2011, Imran Shamhad (sid@projekt-turm.de)
# $Id: $HidTEMPer.pl
#*

BEGIN { push @INC, '/root/dezentrale-klima/munin' }

use strict;
use warnings;

use sensors;
use Munin::Plugin;

my $sensor;
#
#print "$sensor\n";
#print $sensor=~s\./ds1820_\\;

if( !($0=~ m\ds1820_(.*)\) ){
	die "unable to read ID of DS1820 from filename";
}
$sensor = $1;

if (defined $ARGV[0] && $ARGV[0] eq 'autoconf') {
	if( !(ds1820Temp($sensor) eq "U") ){
		print "yes\n";
		exit(0);
	} else {
		print "no\n";
		exit(1);
	}
}

if (defined $ARGV[0] && $ARGV[0] eq 'config') {
print <<EOM;
graph_title			DS1820 $sensor temperature
graph_args			--base 1000 -l 0
graph_info			This graph shows the temperature of DS1820 $sensor in degrees celsius. 
graph_category		sensors
graph_vlabel		temp in °C
$sensor.label		DS1820 $sensor Temperature
$sensor.warning		15.0:30.0
$sensor.critical	10.0:40.0
EOM
exit(0);
}
else{
	print "$sensor.value ", ds1820Temp($sensor);
}
